LOCAL_DB_URL: jdbc:mysql://localhost:3306/ggamja?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
LOCAL_DB_USER: root
LOCAL_DB_PASSWORD: chaedbkey111!
PROD_DB_URL: jdbc:mysql://ggamja-db.cfww4eyigvf4.ap-northeast-2.rds.amazonaws.com:3306/ggamja?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
PROD_DB_USER: admin
PROD_DB_PASSWORD: ggamja01