spring:
  application:
    name: ggamja
  profiles:
    group:
      local: db-local, port-local, common
      prod: db-prod, port-prod, common
#    active: local
---

# local DB
spring:
  config:
    activate:
      on-profile: db-local

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
---

#prod DB
spring:
  config:
    activate:
      on-profile: db-prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect



---
# prod ?? ?? ??
spring:
  config:
    activate:
      on-profile: port-prod

server:
  port: 8080
  servlet:
    context-path: /

---
# ?? ??
spring:
  config:
    activate:
      on-profile: common

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

